language: node_js
dist: trusty
sudo: false

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

install:
  - npm i @angular/cli@7.3.6 -g
  - npm i

script:
  - ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master